In [1]:
import numpy as np
from matplotlib import pyplot as plt

In [10]:
weights = np.zeros(shape=(4,2,20), dtype=int)

In [11]:
weights

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

In [22]:
for i in range(0,4):
    print(i)
    for j in range(0,2):
        print( "%d,%d" % (i,j))
        for k in range(0,20):
            print( "%d,%d,%d" % (i,j,k))
            weights[i,j,k] = 10000*(i+1) + 1000*j + k

0
0,0
0,0,0
0,0,1
0,0,2
0,0,3
0,0,4
0,0,5
0,0,6
0,0,7
0,0,8
0,0,9
0,0,10
0,0,11
0,0,12
0,0,13
0,0,14
0,0,15
0,0,16
0,0,17
0,0,18
0,0,19
0,1
0,1,0
0,1,1
0,1,2
0,1,3
0,1,4
0,1,5
0,1,6
0,1,7
0,1,8
0,1,9
0,1,10
0,1,11
0,1,12
0,1,13
0,1,14
0,1,15
0,1,16
0,1,17
0,1,18
0,1,19
1
1,0
1,0,0
1,0,1
1,0,2
1,0,3
1,0,4
1,0,5
1,0,6
1,0,7
1,0,8
1,0,9
1,0,10
1,0,11
1,0,12
1,0,13
1,0,14
1,0,15
1,0,16
1,0,17
1,0,18
1,0,19
1,1
1,1,0
1,1,1
1,1,2
1,1,3
1,1,4
1,1,5
1,1,6
1,1,7
1,1,8
1,1,9
1,1,10
1,1,11
1,1,12
1,1,13
1,1,14
1,1,15
1,1,16
1,1,17
1,1,18
1,1,19
2
2,0
2,0,0
2,0,1
2,0,2
2,0,3
2,0,4
2,0,5
2,0,6
2,0,7
2,0,8
2,0,9
2,0,10
2,0,11
2,0,12
2,0,13
2,0,14
2,0,15
2,0,16
2,0,17
2,0,18
2,0,19
2,1
2,1,0
2,1,1
2,1,2
2,1,3
2,1,4
2,1,5
2,1,6
2,1,7
2,1,8
2,1,9
2,1,10
2,1,11
2,1,12
2,1,13
2,1,14
2,1,15
2,1,16
2,1,17
2,1,18
2,1,19
3
3,0
3,0,0
3,0,1
3,0,2
3,0,3
3,0,4
3,0,5
3,0,6
3,0,7
3,0,8
3,0,9
3,0,10
3,0,11
3,0,12
3,0,13
3,0,14
3,0,15
3,0,16
3,0,17
3,0,18
3,0,19
3,1
3,1,0
3,1,1
3,1,2
3,1,3
3,1,4
3,1,5
3,1,6
3,1,7
3,

In [23]:
weights

array([[[10000, 10001, 10002, 10003, 10004, 10005, 10006, 10007, 10008,
         10009, 10010, 10011, 10012, 10013, 10014, 10015, 10016, 10017,
         10018, 10019],
        [11000, 11001, 11002, 11003, 11004, 11005, 11006, 11007, 11008,
         11009, 11010, 11011, 11012, 11013, 11014, 11015, 11016, 11017,
         11018, 11019]],

       [[20000, 20001, 20002, 20003, 20004, 20005, 20006, 20007, 20008,
         20009, 20010, 20011, 20012, 20013, 20014, 20015, 20016, 20017,
         20018, 20019],
        [21000, 21001, 21002, 21003, 21004, 21005, 21006, 21007, 21008,
         21009, 21010, 21011, 21012, 21013, 21014, 21015, 21016, 21017,
         21018, 21019]],

       [[30000, 30001, 30002, 30003, 30004, 30005, 30006, 30007, 30008,
         30009, 30010, 30011, 30012, 30013, 30014, 30015, 30016, 30017,
         30018, 30019],
        [31000, 31001, 31002, 31003, 31004, 31005, 31006, 31007, 31008,
         31009, 31010, 31011, 31012, 31013, 31014, 31015, 31016, 31017,
         310

In [24]:
weights[0,0,:]

array([10000, 10001, 10002, 10003, 10004, 10005, 10006, 10007, 10008,
       10009, 10010, 10011, 10012, 10013, 10014, 10015, 10016, 10017,
       10018, 10019])

In [25]:
weights[0,1:2,:]

array([[11000, 11001, 11002, 11003, 11004, 11005, 11006, 11007, 11008,
        11009, 11010, 11011, 11012, 11013, 11014, 11015, 11016, 11017,
        11018, 11019]])

In [26]:
weights[0,1,:]

array([11000, 11001, 11002, 11003, 11004, 11005, 11006, 11007, 11008,
       11009, 11010, 11011, 11012, 11013, 11014, 11015, 11016, 11017,
       11018, 11019])

In [27]:
weights[0,:1,:]

array([[10000, 10001, 10002, 10003, 10004, 10005, 10006, 10007, 10008,
        10009, 10010, 10011, 10012, 10013, 10014, 10015, 10016, 10017,
        10018, 10019]])

In [28]:
weights[0,0,:]

array([10000, 10001, 10002, 10003, 10004, 10005, 10006, 10007, 10008,
       10009, 10010, 10011, 10012, 10013, 10014, 10015, 10016, 10017,
       10018, 10019])

In [29]:
weights[0,:2,:]

array([[10000, 10001, 10002, 10003, 10004, 10005, 10006, 10007, 10008,
        10009, 10010, 10011, 10012, 10013, 10014, 10015, 10016, 10017,
        10018, 10019],
       [11000, 11001, 11002, 11003, 11004, 11005, 11006, 11007, 11008,
        11009, 11010, 11011, 11012, 11013, 11014, 11015, 11016, 11017,
        11018, 11019]])

In [30]:
weights[:1,0,:]

array([[10000, 10001, 10002, 10003, 10004, 10005, 10006, 10007, 10008,
        10009, 10010, 10011, 10012, 10013, 10014, 10015, 10016, 10017,
        10018, 10019]])

In [31]:
weights[:2,0,:]

array([[10000, 10001, 10002, 10003, 10004, 10005, 10006, 10007, 10008,
        10009, 10010, 10011, 10012, 10013, 10014, 10015, 10016, 10017,
        10018, 10019],
       [20000, 20001, 20002, 20003, 20004, 20005, 20006, 20007, 20008,
        20009, 20010, 20011, 20012, 20013, 20014, 20015, 20016, 20017,
        20018, 20019]])

In [1]:
time()

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.29 µs


()

In [4]:
from time import gmtime, strftime
gmtime()

time.struct_time(tm_year=2023, tm_mon=1, tm_mday=27, tm_hour=2, tm_min=7, tm_sec=9, tm_wday=4, tm_yday=27, tm_isdst=0)

In [5]:
print (strftime("%Y-%m-%d %H:%M:%S", gmtime()))

2023-01-27 02:07:51


In [7]:
import time
from stopwatch import Stopwatch, profile

In [8]:
stopwatch = Stopwatch()
stopwatch.start()
time.sleep(3.0)
stopwatch.stop()
print(stopwatch.elapsed)

3.003136900952086


In [10]:
stopwatch.reset()


In [11]:
stopwatch.elapsed

0

In [12]:
stopwatch.start()

In [13]:
stopwatch.elapsed

6.536700087948702

In [14]:
stopwatch.elapsed

13.836261246004142

In [15]:
stopwatch.stop()


In [16]:
stopwatch.elapsed

24.281306307995692